name: update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: run scraper
      run: python scraper/scraper.py

    - name: commit new data
      run: |
        git config --global user.name "bot"
        git config --global user.email "bot@github.com"
        git add data.json
        git commit -m "update data" || echo "no changes"
        git push
